### ISSUE TITLE
Run script after build regardless of specific file changed?

### ISSUE THREAD

**Issue by illepic** [PeterShershov/webpack-noodle-plugin#1]
I'm looking for the option to run a script after webpack build regardless of specific file changes. Can this plugin accomplish this?

**Comment by PeterShershov** [comment]
Hey,
You can accomplish that with [webpack-shell-plugin](https://github.com/1337programming/webpack-shell-plugin).
There's an option to run a shell command before or after the execution.

**Comment by illepic** [comment]
Thank you!
